image: node:18

stages:
  - build
  - deploy

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - npm install
    - npm run build
    - npm run export
    - docker build -t registry.gitlab.com/stt-terpadu-nurul-fikri/devops/242/kong-digong/uaskongdigong:latest .
    - docker push registry.gitlab.com/stt-terpadu-nurul-fikri/devops/242/kong-digong/uaskongdigong:latest

deploy:
  stage: deploy
  script:
    - curl -X POST http://192.168.1.7:8080/gitlab/build?token=otomaton-token
