image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - deploy

before_script:
  - docker info

build-image:
  stage: build
  script:
    - docker build -t registry.gitlab.com/<username>/otomaton-dealer:latest .
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - docker push registry.gitlab.com/<username>/otomaton-dealer:latest

deploy:
  stage: deploy
  script:
    - curl -X POST http://192.168.1.7:8080/gitlab/build?token=otomaton-token
